### ISSUE TITLE
Release `IntsAreEqual` and `IntsAreNotEqual` validators

### ISSUE THREAD

**Issue by Schparky** [gobuffalo/validate#16]
I would like to use `IntsAreNotEqual` that was added in 2018, but there have been no releases since before that. Is there something holding this back from being released?

**Comment by markbates** [comment]
@Schparky sorry about that. I didn't realize they weren't. I've released `v2.0.4` to fix that. I've also opened #17 to bring `go.mod` support.

**Comment by Schparky** [comment]
Thank you!
